# Generated by Django 5.0.7 on 2025-11-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_registropie_payload_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='informefamilia',
            name='pdf_generado',
            field=models.FileField(blank=True, null=True, upload_to='informes_familia/'),
        ),
        migrations.AddField(
            model_name='informefamiliaentrega',
            name='nombre_social',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
