# Generated by Django 5.0.7 on 2025-11-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_informefamilia_pdf_generado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='antecedentesalud',
            name='pdf_generado',
            field=models.FileField(blank=True, null=True, upload_to='antecedentes_salud/'),
        ),
    ]
